#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfPhotoTransfert
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Autofab")]
	public partial class DataAutofab6DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOMMANDE(COMMANDE instance);
    partial void UpdateCOMMANDE(COMMANDE instance);
    partial void DeleteCOMMANDE(COMMANDE instance);
    partial void InsertDOCUMENT(DOCUMENT instance);
    partial void UpdateDOCUMENT(DOCUMENT instance);
    partial void DeleteDOCUMENT(DOCUMENT instance);
    #endregion
		
		public DataAutofab6DataContext() : 
				base(global::CfPhotoTransfert.Properties.Settings.Default.AutofabConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutofab6DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutofab6DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutofab6DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAutofab6DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COMMANDE> COMMANDEs
		{
			get
			{
				return this.GetTable<COMMANDE>();
			}
		}
		
		public System.Data.Linq.Table<DOCUMENT> DOCUMENTs
		{
			get
			{
				return this.GetTable<DOCUMENT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMANDE")]
	public partial class COMMANDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _COSEQ;
		
		private System.Nullable<int> _CLIENT;
		
		private string _CLIENT_CLCODE;
		
		private string _CLIENT_CLNOM;
		
		private System.Nullable<int> _VENDEUR;
		
		private string _VENDEUR_VENOM;
		
		private System.Nullable<int> _ADRLIV;
		
		private string _ADRLIV_ALSOINDE;
		
		private string _ADRLIV_ALNOM;
		
		private string _ADRLIV_ALADR1;
		
		private string _ADRLIV_ALADR2;
		
		private string _ADRLIV_ALADR3;
		
		private string _ADRLIV_ALADR4;
		
		private string _ADRLIV_ALADR5;
		
		private string _ADRLIV_ALCONTACT;
		
		private string _ADRLIV_ALTEL;
		
		private string _ADRLIV_ALFAX;
		
		private string _ADRLIV_ALCELLULAIRE;
		
		private string _ADRLIV_ALEMAIL;
		
		private System.Nullable<int> _ADRLIV_AlDelLiv;
		
		private System.Nullable<int> _ADRLIV_CIE;
		
		private string _ADRLIV_CIE_CODE;
		
		private string _ADRLIV_CIE_NOM;
		
		private System.Nullable<int> _TERRITOIRE;
		
		private string _TERRITOIRE_TTDESC_P;
		
		private string _TERRITOIRE_TTDESC_S;
		
		private System.Nullable<int> _FOURNISSEUR;
		
		private string _FOURNISSEUR_FOCODE;
		
		private string _FOURNISSEUR_FONOM;
		
		private System.Nullable<int> _CONDTRANS;
		
		private string _CONDTRANS_COTCODE;
		
		private string _CONDTRANS_COTDESC1;
		
		private string _CONDTRANS_COTDESC2;
		
		private string _CONDTRANS_COTDESC3;
		
		private System.Nullable<int> _FM_LANGUE;
		
		private System.Nullable<int> _CODETAXE;
		
		private string _CODETAXE_CTDESC_P;
		
		private string _CODETAXE_CTDESC_S;
		
		private string _CONOTRANS;
		
		private string _CONOPO;
		
		private System.Nullable<System.DateTime> _COREQUISDATE;
		
		private System.Nullable<char> _COTYPE;
		
		private System.Nullable<System.DateTime> _COSOUMDATE;
		
		private System.Nullable<System.DateTime> _COCOMDATE;
		
		private int _COSTSEQ;
		
		private System.Nullable<int> _CONOITEMRENDU;
		
		private string _CONOCOMMACOMBA;
		
		private double _COCOUTTRANSP;
		
		private string _CONOTE;
		
		private double _CLIENT_CLESCOMPTE;
		
		private System.Nullable<int> _CLIENT_CLALCSEQ;
		
		private string _CONOTE_EXP;
		
		private string _ADRLIV_ALCOMPTETRANS;
		
		private System.Nullable<int> _DEVISES;
		
		private string _DEVISES_DEVCODE;
		
		private string _DEVISES_DEVDESC_P;
		
		private string _DEVISES_DEVDESC_S;
		
		private bool _ADRLIV_ALTRANSTAXAB;
		
		private double _DEVISES_DEVTAUX;
		
		private double _CODETAXE_CTNTAXE1;
		
		private double _CODETAXE_CTNTAXE2;
		
		private double _CODETAXE_CTNTAXE3;
		
		private string _CODETAXE_CTAXE1;
		
		private string _CODETAXE_CTAXE2;
		
		private string _CODETAXE_CTAXE3;
		
		private bool _CODETAXE_CTAXECUMUL;
		
		private string _CODETAXE_CTCODE;
		
		private string _COPROJET;
		
		private System.Nullable<bool> _COEXPORTE;
		
		private string _COACHETEUR;
		
		private string _COUSAGER;
		
		private string _COAUSOIN_DE;
		
		private double _COTAXE1;
		
		private double _COTAXE2;
		
		private double _COTAXE3;
		
		private double _COMONTANTTAXABLE;
		
		private double _COSOUSTOTAL;
		
		private bool _CLIENT_CLINDEFINI;
		
		private System.Nullable<int> _ADRFAC;
		
		private string _ADRFAC_ALSOINDE;
		
		private string _ADRFAC_ALNOM;
		
		private string _ADRFAC_ALADR1;
		
		private string _ADRFAC_ALADR2;
		
		private string _ADRFAC_ALADR3;
		
		private string _ADRFAC_ALADR4;
		
		private string _ADRFAC_ALADR5;
		
		private System.Nullable<int> _ADRFAC_FM_LANGUE;
		
		private string _TERRITOIRE_TTCODE;
		
		private string _ADRLIV_ALEXTENSION;
		
		private System.Nullable<int> _FOURNISSEUR_ADRLIV;
		
		private double _COTOTALITEM;
		
		private string _CONOTE_TRANSPORT;
		
		private System.Nullable<int> _CONTACT;
		
		private System.Nullable<int> _CLIENT_FAC;
		
		private string _CLIENT_FAC_CLCODE;
		
		private string _CLIENT_FAC_CLNOM;
		
		private string _COCHEMCOPIEDESS_SE;
		
		private bool _COPRIX_FIXE;
		
		private System.Nullable<int> _RAISON;
		
		private string _RAISON_RRCODE;
		
		private string _RAISON_RRDESC_P;
		
		private string _RAISON_RRDESC_S;
		
		private string _CONOCONTRAT;
		
		private System.Nullable<System.DateTime> _COCLOSEDATE;
		
		private string _ADRFAC_ALFAX;
		
		private string _ADRFAC_ALTEL;
		
		private string _ADRFAC_ALEMAIL;
		
		private string _ADRFAC_ALCONTACT;
		
		private string _ADRFAC_ALCELLULAIRE;
		
		private string _ADRFAC_ALTELAUTRE;
		
		private System.Nullable<int> _COSEQ_PERE;
		
		private int _COCOMPTEUR_REVISION;
		
		private string _COREVNOTRANS;
		
		private string _COINFOSUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOSEQChanging(int value);
    partial void OnCOSEQChanged();
    partial void OnCLIENTChanging(System.Nullable<int> value);
    partial void OnCLIENTChanged();
    partial void OnCLIENT_CLCODEChanging(string value);
    partial void OnCLIENT_CLCODEChanged();
    partial void OnCLIENT_CLNOMChanging(string value);
    partial void OnCLIENT_CLNOMChanged();
    partial void OnVENDEURChanging(System.Nullable<int> value);
    partial void OnVENDEURChanged();
    partial void OnVENDEUR_VENOMChanging(string value);
    partial void OnVENDEUR_VENOMChanged();
    partial void OnADRLIVChanging(System.Nullable<int> value);
    partial void OnADRLIVChanged();
    partial void OnADRLIV_ALSOINDEChanging(string value);
    partial void OnADRLIV_ALSOINDEChanged();
    partial void OnADRLIV_ALNOMChanging(string value);
    partial void OnADRLIV_ALNOMChanged();
    partial void OnADRLIV_ALADR1Changing(string value);
    partial void OnADRLIV_ALADR1Changed();
    partial void OnADRLIV_ALADR2Changing(string value);
    partial void OnADRLIV_ALADR2Changed();
    partial void OnADRLIV_ALADR3Changing(string value);
    partial void OnADRLIV_ALADR3Changed();
    partial void OnADRLIV_ALADR4Changing(string value);
    partial void OnADRLIV_ALADR4Changed();
    partial void OnADRLIV_ALADR5Changing(string value);
    partial void OnADRLIV_ALADR5Changed();
    partial void OnADRLIV_ALCONTACTChanging(string value);
    partial void OnADRLIV_ALCONTACTChanged();
    partial void OnADRLIV_ALTELChanging(string value);
    partial void OnADRLIV_ALTELChanged();
    partial void OnADRLIV_ALFAXChanging(string value);
    partial void OnADRLIV_ALFAXChanged();
    partial void OnADRLIV_ALCELLULAIREChanging(string value);
    partial void OnADRLIV_ALCELLULAIREChanged();
    partial void OnADRLIV_ALEMAILChanging(string value);
    partial void OnADRLIV_ALEMAILChanged();
    partial void OnADRLIV_AlDelLivChanging(System.Nullable<int> value);
    partial void OnADRLIV_AlDelLivChanged();
    partial void OnADRLIV_CIEChanging(System.Nullable<int> value);
    partial void OnADRLIV_CIEChanged();
    partial void OnADRLIV_CIE_CODEChanging(string value);
    partial void OnADRLIV_CIE_CODEChanged();
    partial void OnADRLIV_CIE_NOMChanging(string value);
    partial void OnADRLIV_CIE_NOMChanged();
    partial void OnTERRITOIREChanging(System.Nullable<int> value);
    partial void OnTERRITOIREChanged();
    partial void OnTERRITOIRE_TTDESC_PChanging(string value);
    partial void OnTERRITOIRE_TTDESC_PChanged();
    partial void OnTERRITOIRE_TTDESC_SChanging(string value);
    partial void OnTERRITOIRE_TTDESC_SChanged();
    partial void OnFOURNISSEURChanging(System.Nullable<int> value);
    partial void OnFOURNISSEURChanged();
    partial void OnFOURNISSEUR_FOCODEChanging(string value);
    partial void OnFOURNISSEUR_FOCODEChanged();
    partial void OnFOURNISSEUR_FONOMChanging(string value);
    partial void OnFOURNISSEUR_FONOMChanged();
    partial void OnCONDTRANSChanging(System.Nullable<int> value);
    partial void OnCONDTRANSChanged();
    partial void OnCONDTRANS_COTCODEChanging(string value);
    partial void OnCONDTRANS_COTCODEChanged();
    partial void OnCONDTRANS_COTDESC1Changing(string value);
    partial void OnCONDTRANS_COTDESC1Changed();
    partial void OnCONDTRANS_COTDESC2Changing(string value);
    partial void OnCONDTRANS_COTDESC2Changed();
    partial void OnCONDTRANS_COTDESC3Changing(string value);
    partial void OnCONDTRANS_COTDESC3Changed();
    partial void OnFM_LANGUEChanging(System.Nullable<int> value);
    partial void OnFM_LANGUEChanged();
    partial void OnCODETAXEChanging(System.Nullable<int> value);
    partial void OnCODETAXEChanged();
    partial void OnCODETAXE_CTDESC_PChanging(string value);
    partial void OnCODETAXE_CTDESC_PChanged();
    partial void OnCODETAXE_CTDESC_SChanging(string value);
    partial void OnCODETAXE_CTDESC_SChanged();
    partial void OnCONOTRANSChanging(string value);
    partial void OnCONOTRANSChanged();
    partial void OnCONOPOChanging(string value);
    partial void OnCONOPOChanged();
    partial void OnCOREQUISDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCOREQUISDATEChanged();
    partial void OnCOTYPEChanging(System.Nullable<char> value);
    partial void OnCOTYPEChanged();
    partial void OnCOSOUMDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCOSOUMDATEChanged();
    partial void OnCOCOMDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCOCOMDATEChanged();
    partial void OnCOSTSEQChanging(int value);
    partial void OnCOSTSEQChanged();
    partial void OnCONOITEMRENDUChanging(System.Nullable<int> value);
    partial void OnCONOITEMRENDUChanged();
    partial void OnCONOCOMMACOMBAChanging(string value);
    partial void OnCONOCOMMACOMBAChanged();
    partial void OnCOCOUTTRANSPChanging(double value);
    partial void OnCOCOUTTRANSPChanged();
    partial void OnCONOTEChanging(string value);
    partial void OnCONOTEChanged();
    partial void OnCLIENT_CLESCOMPTEChanging(double value);
    partial void OnCLIENT_CLESCOMPTEChanged();
    partial void OnCLIENT_CLALCSEQChanging(System.Nullable<int> value);
    partial void OnCLIENT_CLALCSEQChanged();
    partial void OnCONOTE_EXPChanging(string value);
    partial void OnCONOTE_EXPChanged();
    partial void OnADRLIV_ALCOMPTETRANSChanging(string value);
    partial void OnADRLIV_ALCOMPTETRANSChanged();
    partial void OnDEVISESChanging(System.Nullable<int> value);
    partial void OnDEVISESChanged();
    partial void OnDEVISES_DEVCODEChanging(string value);
    partial void OnDEVISES_DEVCODEChanged();
    partial void OnDEVISES_DEVDESC_PChanging(string value);
    partial void OnDEVISES_DEVDESC_PChanged();
    partial void OnDEVISES_DEVDESC_SChanging(string value);
    partial void OnDEVISES_DEVDESC_SChanged();
    partial void OnADRLIV_ALTRANSTAXABChanging(bool value);
    partial void OnADRLIV_ALTRANSTAXABChanged();
    partial void OnDEVISES_DEVTAUXChanging(double value);
    partial void OnDEVISES_DEVTAUXChanged();
    partial void OnCODETAXE_CTNTAXE1Changing(double value);
    partial void OnCODETAXE_CTNTAXE1Changed();
    partial void OnCODETAXE_CTNTAXE2Changing(double value);
    partial void OnCODETAXE_CTNTAXE2Changed();
    partial void OnCODETAXE_CTNTAXE3Changing(double value);
    partial void OnCODETAXE_CTNTAXE3Changed();
    partial void OnCODETAXE_CTAXE1Changing(string value);
    partial void OnCODETAXE_CTAXE1Changed();
    partial void OnCODETAXE_CTAXE2Changing(string value);
    partial void OnCODETAXE_CTAXE2Changed();
    partial void OnCODETAXE_CTAXE3Changing(string value);
    partial void OnCODETAXE_CTAXE3Changed();
    partial void OnCODETAXE_CTAXECUMULChanging(bool value);
    partial void OnCODETAXE_CTAXECUMULChanged();
    partial void OnCODETAXE_CTCODEChanging(string value);
    partial void OnCODETAXE_CTCODEChanged();
    partial void OnCOPROJETChanging(string value);
    partial void OnCOPROJETChanged();
    partial void OnCOEXPORTEChanging(System.Nullable<bool> value);
    partial void OnCOEXPORTEChanged();
    partial void OnCOACHETEURChanging(string value);
    partial void OnCOACHETEURChanged();
    partial void OnCOUSAGERChanging(string value);
    partial void OnCOUSAGERChanged();
    partial void OnCOAUSOIN_DEChanging(string value);
    partial void OnCOAUSOIN_DEChanged();
    partial void OnCOTAXE1Changing(double value);
    partial void OnCOTAXE1Changed();
    partial void OnCOTAXE2Changing(double value);
    partial void OnCOTAXE2Changed();
    partial void OnCOTAXE3Changing(double value);
    partial void OnCOTAXE3Changed();
    partial void OnCOMONTANTTAXABLEChanging(double value);
    partial void OnCOMONTANTTAXABLEChanged();
    partial void OnCOSOUSTOTALChanging(double value);
    partial void OnCOSOUSTOTALChanged();
    partial void OnCLIENT_CLINDEFINIChanging(bool value);
    partial void OnCLIENT_CLINDEFINIChanged();
    partial void OnADRFACChanging(System.Nullable<int> value);
    partial void OnADRFACChanged();
    partial void OnADRFAC_ALSOINDEChanging(string value);
    partial void OnADRFAC_ALSOINDEChanged();
    partial void OnADRFAC_ALNOMChanging(string value);
    partial void OnADRFAC_ALNOMChanged();
    partial void OnADRFAC_ALADR1Changing(string value);
    partial void OnADRFAC_ALADR1Changed();
    partial void OnADRFAC_ALADR2Changing(string value);
    partial void OnADRFAC_ALADR2Changed();
    partial void OnADRFAC_ALADR3Changing(string value);
    partial void OnADRFAC_ALADR3Changed();
    partial void OnADRFAC_ALADR4Changing(string value);
    partial void OnADRFAC_ALADR4Changed();
    partial void OnADRFAC_ALADR5Changing(string value);
    partial void OnADRFAC_ALADR5Changed();
    partial void OnADRFAC_FM_LANGUEChanging(System.Nullable<int> value);
    partial void OnADRFAC_FM_LANGUEChanged();
    partial void OnTERRITOIRE_TTCODEChanging(string value);
    partial void OnTERRITOIRE_TTCODEChanged();
    partial void OnADRLIV_ALEXTENSIONChanging(string value);
    partial void OnADRLIV_ALEXTENSIONChanged();
    partial void OnFOURNISSEUR_ADRLIVChanging(System.Nullable<int> value);
    partial void OnFOURNISSEUR_ADRLIVChanged();
    partial void OnCOTOTALITEMChanging(double value);
    partial void OnCOTOTALITEMChanged();
    partial void OnCONOTE_TRANSPORTChanging(string value);
    partial void OnCONOTE_TRANSPORTChanged();
    partial void OnCONTACTChanging(System.Nullable<int> value);
    partial void OnCONTACTChanged();
    partial void OnCLIENT_FACChanging(System.Nullable<int> value);
    partial void OnCLIENT_FACChanged();
    partial void OnCLIENT_FAC_CLCODEChanging(string value);
    partial void OnCLIENT_FAC_CLCODEChanged();
    partial void OnCLIENT_FAC_CLNOMChanging(string value);
    partial void OnCLIENT_FAC_CLNOMChanged();
    partial void OnCOCHEMCOPIEDESS_SEChanging(string value);
    partial void OnCOCHEMCOPIEDESS_SEChanged();
    partial void OnCOPRIX_FIXEChanging(bool value);
    partial void OnCOPRIX_FIXEChanged();
    partial void OnRAISONChanging(System.Nullable<int> value);
    partial void OnRAISONChanged();
    partial void OnRAISON_RRCODEChanging(string value);
    partial void OnRAISON_RRCODEChanged();
    partial void OnRAISON_RRDESC_PChanging(string value);
    partial void OnRAISON_RRDESC_PChanged();
    partial void OnRAISON_RRDESC_SChanging(string value);
    partial void OnRAISON_RRDESC_SChanged();
    partial void OnCONOCONTRATChanging(string value);
    partial void OnCONOCONTRATChanged();
    partial void OnCOCLOSEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCOCLOSEDATEChanged();
    partial void OnADRFAC_ALFAXChanging(string value);
    partial void OnADRFAC_ALFAXChanged();
    partial void OnADRFAC_ALTELChanging(string value);
    partial void OnADRFAC_ALTELChanged();
    partial void OnADRFAC_ALEMAILChanging(string value);
    partial void OnADRFAC_ALEMAILChanged();
    partial void OnADRFAC_ALCONTACTChanging(string value);
    partial void OnADRFAC_ALCONTACTChanged();
    partial void OnADRFAC_ALCELLULAIREChanging(string value);
    partial void OnADRFAC_ALCELLULAIREChanged();
    partial void OnADRFAC_ALTELAUTREChanging(string value);
    partial void OnADRFAC_ALTELAUTREChanged();
    partial void OnCOSEQ_PEREChanging(System.Nullable<int> value);
    partial void OnCOSEQ_PEREChanged();
    partial void OnCOCOMPTEUR_REVISIONChanging(int value);
    partial void OnCOCOMPTEUR_REVISIONChanged();
    partial void OnCOREVNOTRANSChanging(string value);
    partial void OnCOREVNOTRANSChanged();
    partial void OnCOINFOSUPChanging(string value);
    partial void OnCOINFOSUPChanged();
    #endregion
		
		public COMMANDE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSEQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int COSEQ
		{
			get
			{
				return this._COSEQ;
			}
			set
			{
				if ((this._COSEQ != value))
				{
					this.OnCOSEQChanging(value);
					this.SendPropertyChanging();
					this._COSEQ = value;
					this.SendPropertyChanged("COSEQ");
					this.OnCOSEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT", DbType="Int")]
		public System.Nullable<int> CLIENT
		{
			get
			{
				return this._CLIENT;
			}
			set
			{
				if ((this._CLIENT != value))
				{
					this.OnCLIENTChanging(value);
					this.SendPropertyChanging();
					this._CLIENT = value;
					this.SendPropertyChanged("CLIENT");
					this.OnCLIENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_CLCODE", DbType="VarChar(20)")]
		public string CLIENT_CLCODE
		{
			get
			{
				return this._CLIENT_CLCODE;
			}
			set
			{
				if ((this._CLIENT_CLCODE != value))
				{
					this.OnCLIENT_CLCODEChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_CLCODE = value;
					this.SendPropertyChanged("CLIENT_CLCODE");
					this.OnCLIENT_CLCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_CLNOM", DbType="VarChar(50)")]
		public string CLIENT_CLNOM
		{
			get
			{
				return this._CLIENT_CLNOM;
			}
			set
			{
				if ((this._CLIENT_CLNOM != value))
				{
					this.OnCLIENT_CLNOMChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_CLNOM = value;
					this.SendPropertyChanged("CLIENT_CLNOM");
					this.OnCLIENT_CLNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDEUR", DbType="Int")]
		public System.Nullable<int> VENDEUR
		{
			get
			{
				return this._VENDEUR;
			}
			set
			{
				if ((this._VENDEUR != value))
				{
					this.OnVENDEURChanging(value);
					this.SendPropertyChanging();
					this._VENDEUR = value;
					this.SendPropertyChanged("VENDEUR");
					this.OnVENDEURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDEUR_VENOM", DbType="VarChar(50)")]
		public string VENDEUR_VENOM
		{
			get
			{
				return this._VENDEUR_VENOM;
			}
			set
			{
				if ((this._VENDEUR_VENOM != value))
				{
					this.OnVENDEUR_VENOMChanging(value);
					this.SendPropertyChanging();
					this._VENDEUR_VENOM = value;
					this.SendPropertyChanged("VENDEUR_VENOM");
					this.OnVENDEUR_VENOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV", DbType="Int")]
		public System.Nullable<int> ADRLIV
		{
			get
			{
				return this._ADRLIV;
			}
			set
			{
				if ((this._ADRLIV != value))
				{
					this.OnADRLIVChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV = value;
					this.SendPropertyChanged("ADRLIV");
					this.OnADRLIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALSOINDE", DbType="VarChar(60)")]
		public string ADRLIV_ALSOINDE
		{
			get
			{
				return this._ADRLIV_ALSOINDE;
			}
			set
			{
				if ((this._ADRLIV_ALSOINDE != value))
				{
					this.OnADRLIV_ALSOINDEChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALSOINDE = value;
					this.SendPropertyChanged("ADRLIV_ALSOINDE");
					this.OnADRLIV_ALSOINDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALNOM", DbType="VarChar(50)")]
		public string ADRLIV_ALNOM
		{
			get
			{
				return this._ADRLIV_ALNOM;
			}
			set
			{
				if ((this._ADRLIV_ALNOM != value))
				{
					this.OnADRLIV_ALNOMChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALNOM = value;
					this.SendPropertyChanged("ADRLIV_ALNOM");
					this.OnADRLIV_ALNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALADR1", DbType="VarChar(50)")]
		public string ADRLIV_ALADR1
		{
			get
			{
				return this._ADRLIV_ALADR1;
			}
			set
			{
				if ((this._ADRLIV_ALADR1 != value))
				{
					this.OnADRLIV_ALADR1Changing(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALADR1 = value;
					this.SendPropertyChanged("ADRLIV_ALADR1");
					this.OnADRLIV_ALADR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALADR2", DbType="VarChar(50)")]
		public string ADRLIV_ALADR2
		{
			get
			{
				return this._ADRLIV_ALADR2;
			}
			set
			{
				if ((this._ADRLIV_ALADR2 != value))
				{
					this.OnADRLIV_ALADR2Changing(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALADR2 = value;
					this.SendPropertyChanged("ADRLIV_ALADR2");
					this.OnADRLIV_ALADR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALADR3", DbType="VarChar(50)")]
		public string ADRLIV_ALADR3
		{
			get
			{
				return this._ADRLIV_ALADR3;
			}
			set
			{
				if ((this._ADRLIV_ALADR3 != value))
				{
					this.OnADRLIV_ALADR3Changing(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALADR3 = value;
					this.SendPropertyChanged("ADRLIV_ALADR3");
					this.OnADRLIV_ALADR3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALADR4", DbType="VarChar(50)")]
		public string ADRLIV_ALADR4
		{
			get
			{
				return this._ADRLIV_ALADR4;
			}
			set
			{
				if ((this._ADRLIV_ALADR4 != value))
				{
					this.OnADRLIV_ALADR4Changing(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALADR4 = value;
					this.SendPropertyChanged("ADRLIV_ALADR4");
					this.OnADRLIV_ALADR4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALADR5", DbType="VarChar(50)")]
		public string ADRLIV_ALADR5
		{
			get
			{
				return this._ADRLIV_ALADR5;
			}
			set
			{
				if ((this._ADRLIV_ALADR5 != value))
				{
					this.OnADRLIV_ALADR5Changing(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALADR5 = value;
					this.SendPropertyChanged("ADRLIV_ALADR5");
					this.OnADRLIV_ALADR5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALCONTACT", DbType="VarChar(50)")]
		public string ADRLIV_ALCONTACT
		{
			get
			{
				return this._ADRLIV_ALCONTACT;
			}
			set
			{
				if ((this._ADRLIV_ALCONTACT != value))
				{
					this.OnADRLIV_ALCONTACTChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALCONTACT = value;
					this.SendPropertyChanged("ADRLIV_ALCONTACT");
					this.OnADRLIV_ALCONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALTEL", DbType="VarChar(20)")]
		public string ADRLIV_ALTEL
		{
			get
			{
				return this._ADRLIV_ALTEL;
			}
			set
			{
				if ((this._ADRLIV_ALTEL != value))
				{
					this.OnADRLIV_ALTELChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALTEL = value;
					this.SendPropertyChanged("ADRLIV_ALTEL");
					this.OnADRLIV_ALTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALFAX", DbType="VarChar(20)")]
		public string ADRLIV_ALFAX
		{
			get
			{
				return this._ADRLIV_ALFAX;
			}
			set
			{
				if ((this._ADRLIV_ALFAX != value))
				{
					this.OnADRLIV_ALFAXChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALFAX = value;
					this.SendPropertyChanged("ADRLIV_ALFAX");
					this.OnADRLIV_ALFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALCELLULAIRE", DbType="VarChar(20)")]
		public string ADRLIV_ALCELLULAIRE
		{
			get
			{
				return this._ADRLIV_ALCELLULAIRE;
			}
			set
			{
				if ((this._ADRLIV_ALCELLULAIRE != value))
				{
					this.OnADRLIV_ALCELLULAIREChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALCELLULAIRE = value;
					this.SendPropertyChanged("ADRLIV_ALCELLULAIRE");
					this.OnADRLIV_ALCELLULAIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALEMAIL", DbType="VarChar(50)")]
		public string ADRLIV_ALEMAIL
		{
			get
			{
				return this._ADRLIV_ALEMAIL;
			}
			set
			{
				if ((this._ADRLIV_ALEMAIL != value))
				{
					this.OnADRLIV_ALEMAILChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALEMAIL = value;
					this.SendPropertyChanged("ADRLIV_ALEMAIL");
					this.OnADRLIV_ALEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_AlDelLiv", DbType="Int")]
		public System.Nullable<int> ADRLIV_AlDelLiv
		{
			get
			{
				return this._ADRLIV_AlDelLiv;
			}
			set
			{
				if ((this._ADRLIV_AlDelLiv != value))
				{
					this.OnADRLIV_AlDelLivChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_AlDelLiv = value;
					this.SendPropertyChanged("ADRLIV_AlDelLiv");
					this.OnADRLIV_AlDelLivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_CIE", DbType="Int")]
		public System.Nullable<int> ADRLIV_CIE
		{
			get
			{
				return this._ADRLIV_CIE;
			}
			set
			{
				if ((this._ADRLIV_CIE != value))
				{
					this.OnADRLIV_CIEChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_CIE = value;
					this.SendPropertyChanged("ADRLIV_CIE");
					this.OnADRLIV_CIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_CIE_CODE", DbType="VarChar(20)")]
		public string ADRLIV_CIE_CODE
		{
			get
			{
				return this._ADRLIV_CIE_CODE;
			}
			set
			{
				if ((this._ADRLIV_CIE_CODE != value))
				{
					this.OnADRLIV_CIE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_CIE_CODE = value;
					this.SendPropertyChanged("ADRLIV_CIE_CODE");
					this.OnADRLIV_CIE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_CIE_NOM", DbType="VarChar(50)")]
		public string ADRLIV_CIE_NOM
		{
			get
			{
				return this._ADRLIV_CIE_NOM;
			}
			set
			{
				if ((this._ADRLIV_CIE_NOM != value))
				{
					this.OnADRLIV_CIE_NOMChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_CIE_NOM = value;
					this.SendPropertyChanged("ADRLIV_CIE_NOM");
					this.OnADRLIV_CIE_NOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRITOIRE", DbType="Int")]
		public System.Nullable<int> TERRITOIRE
		{
			get
			{
				return this._TERRITOIRE;
			}
			set
			{
				if ((this._TERRITOIRE != value))
				{
					this.OnTERRITOIREChanging(value);
					this.SendPropertyChanging();
					this._TERRITOIRE = value;
					this.SendPropertyChanged("TERRITOIRE");
					this.OnTERRITOIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRITOIRE_TTDESC_P", DbType="VarChar(50)")]
		public string TERRITOIRE_TTDESC_P
		{
			get
			{
				return this._TERRITOIRE_TTDESC_P;
			}
			set
			{
				if ((this._TERRITOIRE_TTDESC_P != value))
				{
					this.OnTERRITOIRE_TTDESC_PChanging(value);
					this.SendPropertyChanging();
					this._TERRITOIRE_TTDESC_P = value;
					this.SendPropertyChanged("TERRITOIRE_TTDESC_P");
					this.OnTERRITOIRE_TTDESC_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRITOIRE_TTDESC_S", DbType="VarChar(50)")]
		public string TERRITOIRE_TTDESC_S
		{
			get
			{
				return this._TERRITOIRE_TTDESC_S;
			}
			set
			{
				if ((this._TERRITOIRE_TTDESC_S != value))
				{
					this.OnTERRITOIRE_TTDESC_SChanging(value);
					this.SendPropertyChanging();
					this._TERRITOIRE_TTDESC_S = value;
					this.SendPropertyChanged("TERRITOIRE_TTDESC_S");
					this.OnTERRITOIRE_TTDESC_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOURNISSEUR", DbType="Int")]
		public System.Nullable<int> FOURNISSEUR
		{
			get
			{
				return this._FOURNISSEUR;
			}
			set
			{
				if ((this._FOURNISSEUR != value))
				{
					this.OnFOURNISSEURChanging(value);
					this.SendPropertyChanging();
					this._FOURNISSEUR = value;
					this.SendPropertyChanged("FOURNISSEUR");
					this.OnFOURNISSEURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOURNISSEUR_FOCODE", DbType="VarChar(20)")]
		public string FOURNISSEUR_FOCODE
		{
			get
			{
				return this._FOURNISSEUR_FOCODE;
			}
			set
			{
				if ((this._FOURNISSEUR_FOCODE != value))
				{
					this.OnFOURNISSEUR_FOCODEChanging(value);
					this.SendPropertyChanging();
					this._FOURNISSEUR_FOCODE = value;
					this.SendPropertyChanged("FOURNISSEUR_FOCODE");
					this.OnFOURNISSEUR_FOCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOURNISSEUR_FONOM", DbType="VarChar(50)")]
		public string FOURNISSEUR_FONOM
		{
			get
			{
				return this._FOURNISSEUR_FONOM;
			}
			set
			{
				if ((this._FOURNISSEUR_FONOM != value))
				{
					this.OnFOURNISSEUR_FONOMChanging(value);
					this.SendPropertyChanging();
					this._FOURNISSEUR_FONOM = value;
					this.SendPropertyChanged("FOURNISSEUR_FONOM");
					this.OnFOURNISSEUR_FONOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDTRANS", DbType="Int")]
		public System.Nullable<int> CONDTRANS
		{
			get
			{
				return this._CONDTRANS;
			}
			set
			{
				if ((this._CONDTRANS != value))
				{
					this.OnCONDTRANSChanging(value);
					this.SendPropertyChanging();
					this._CONDTRANS = value;
					this.SendPropertyChanged("CONDTRANS");
					this.OnCONDTRANSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDTRANS_COTCODE", DbType="VarChar(2)")]
		public string CONDTRANS_COTCODE
		{
			get
			{
				return this._CONDTRANS_COTCODE;
			}
			set
			{
				if ((this._CONDTRANS_COTCODE != value))
				{
					this.OnCONDTRANS_COTCODEChanging(value);
					this.SendPropertyChanging();
					this._CONDTRANS_COTCODE = value;
					this.SendPropertyChanged("CONDTRANS_COTCODE");
					this.OnCONDTRANS_COTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDTRANS_COTDESC1", DbType="VarChar(50)")]
		public string CONDTRANS_COTDESC1
		{
			get
			{
				return this._CONDTRANS_COTDESC1;
			}
			set
			{
				if ((this._CONDTRANS_COTDESC1 != value))
				{
					this.OnCONDTRANS_COTDESC1Changing(value);
					this.SendPropertyChanging();
					this._CONDTRANS_COTDESC1 = value;
					this.SendPropertyChanged("CONDTRANS_COTDESC1");
					this.OnCONDTRANS_COTDESC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDTRANS_COTDESC2", DbType="VarChar(50)")]
		public string CONDTRANS_COTDESC2
		{
			get
			{
				return this._CONDTRANS_COTDESC2;
			}
			set
			{
				if ((this._CONDTRANS_COTDESC2 != value))
				{
					this.OnCONDTRANS_COTDESC2Changing(value);
					this.SendPropertyChanging();
					this._CONDTRANS_COTDESC2 = value;
					this.SendPropertyChanged("CONDTRANS_COTDESC2");
					this.OnCONDTRANS_COTDESC2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDTRANS_COTDESC3", DbType="VarChar(50)")]
		public string CONDTRANS_COTDESC3
		{
			get
			{
				return this._CONDTRANS_COTDESC3;
			}
			set
			{
				if ((this._CONDTRANS_COTDESC3 != value))
				{
					this.OnCONDTRANS_COTDESC3Changing(value);
					this.SendPropertyChanging();
					this._CONDTRANS_COTDESC3 = value;
					this.SendPropertyChanged("CONDTRANS_COTDESC3");
					this.OnCONDTRANS_COTDESC3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FM_LANGUE", DbType="Int")]
		public System.Nullable<int> FM_LANGUE
		{
			get
			{
				return this._FM_LANGUE;
			}
			set
			{
				if ((this._FM_LANGUE != value))
				{
					this.OnFM_LANGUEChanging(value);
					this.SendPropertyChanging();
					this._FM_LANGUE = value;
					this.SendPropertyChanged("FM_LANGUE");
					this.OnFM_LANGUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE", DbType="Int")]
		public System.Nullable<int> CODETAXE
		{
			get
			{
				return this._CODETAXE;
			}
			set
			{
				if ((this._CODETAXE != value))
				{
					this.OnCODETAXEChanging(value);
					this.SendPropertyChanging();
					this._CODETAXE = value;
					this.SendPropertyChanged("CODETAXE");
					this.OnCODETAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTDESC_P", DbType="VarChar(50)")]
		public string CODETAXE_CTDESC_P
		{
			get
			{
				return this._CODETAXE_CTDESC_P;
			}
			set
			{
				if ((this._CODETAXE_CTDESC_P != value))
				{
					this.OnCODETAXE_CTDESC_PChanging(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTDESC_P = value;
					this.SendPropertyChanged("CODETAXE_CTDESC_P");
					this.OnCODETAXE_CTDESC_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTDESC_S", DbType="VarChar(50)")]
		public string CODETAXE_CTDESC_S
		{
			get
			{
				return this._CODETAXE_CTDESC_S;
			}
			set
			{
				if ((this._CODETAXE_CTDESC_S != value))
				{
					this.OnCODETAXE_CTDESC_SChanging(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTDESC_S = value;
					this.SendPropertyChanged("CODETAXE_CTDESC_S");
					this.OnCODETAXE_CTDESC_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOTRANS", DbType="Char(9)")]
		public string CONOTRANS
		{
			get
			{
				return this._CONOTRANS;
			}
			set
			{
				if ((this._CONOTRANS != value))
				{
					this.OnCONOTRANSChanging(value);
					this.SendPropertyChanging();
					this._CONOTRANS = value;
					this.SendPropertyChanged("CONOTRANS");
					this.OnCONOTRANSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOPO", DbType="VarChar(20)")]
		public string CONOPO
		{
			get
			{
				return this._CONOPO;
			}
			set
			{
				if ((this._CONOPO != value))
				{
					this.OnCONOPOChanging(value);
					this.SendPropertyChanging();
					this._CONOPO = value;
					this.SendPropertyChanged("CONOPO");
					this.OnCONOPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COREQUISDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> COREQUISDATE
		{
			get
			{
				return this._COREQUISDATE;
			}
			set
			{
				if ((this._COREQUISDATE != value))
				{
					this.OnCOREQUISDATEChanging(value);
					this.SendPropertyChanging();
					this._COREQUISDATE = value;
					this.SendPropertyChanged("COREQUISDATE");
					this.OnCOREQUISDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTYPE", DbType="Char(1)")]
		public System.Nullable<char> COTYPE
		{
			get
			{
				return this._COTYPE;
			}
			set
			{
				if ((this._COTYPE != value))
				{
					this.OnCOTYPEChanging(value);
					this.SendPropertyChanging();
					this._COTYPE = value;
					this.SendPropertyChanged("COTYPE");
					this.OnCOTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSOUMDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> COSOUMDATE
		{
			get
			{
				return this._COSOUMDATE;
			}
			set
			{
				if ((this._COSOUMDATE != value))
				{
					this.OnCOSOUMDATEChanging(value);
					this.SendPropertyChanging();
					this._COSOUMDATE = value;
					this.SendPropertyChanged("COSOUMDATE");
					this.OnCOSOUMDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COCOMDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> COCOMDATE
		{
			get
			{
				return this._COCOMDATE;
			}
			set
			{
				if ((this._COCOMDATE != value))
				{
					this.OnCOCOMDATEChanging(value);
					this.SendPropertyChanging();
					this._COCOMDATE = value;
					this.SendPropertyChanged("COCOMDATE");
					this.OnCOCOMDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTSEQ", DbType="Int NOT NULL")]
		public int COSTSEQ
		{
			get
			{
				return this._COSTSEQ;
			}
			set
			{
				if ((this._COSTSEQ != value))
				{
					this.OnCOSTSEQChanging(value);
					this.SendPropertyChanging();
					this._COSTSEQ = value;
					this.SendPropertyChanged("COSTSEQ");
					this.OnCOSTSEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOITEMRENDU", DbType="Int")]
		public System.Nullable<int> CONOITEMRENDU
		{
			get
			{
				return this._CONOITEMRENDU;
			}
			set
			{
				if ((this._CONOITEMRENDU != value))
				{
					this.OnCONOITEMRENDUChanging(value);
					this.SendPropertyChanging();
					this._CONOITEMRENDU = value;
					this.SendPropertyChanged("CONOITEMRENDU");
					this.OnCONOITEMRENDUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOCOMMACOMBA", DbType="VarChar(10)")]
		public string CONOCOMMACOMBA
		{
			get
			{
				return this._CONOCOMMACOMBA;
			}
			set
			{
				if ((this._CONOCOMMACOMBA != value))
				{
					this.OnCONOCOMMACOMBAChanging(value);
					this.SendPropertyChanging();
					this._CONOCOMMACOMBA = value;
					this.SendPropertyChanged("CONOCOMMACOMBA");
					this.OnCONOCOMMACOMBAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COCOUTTRANSP", DbType="Float NOT NULL")]
		public double COCOUTTRANSP
		{
			get
			{
				return this._COCOUTTRANSP;
			}
			set
			{
				if ((this._COCOUTTRANSP != value))
				{
					this.OnCOCOUTTRANSPChanging(value);
					this.SendPropertyChanging();
					this._COCOUTTRANSP = value;
					this.SendPropertyChanged("COCOUTTRANSP");
					this.OnCOCOUTTRANSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOTE", DbType="VarChar(7500)")]
		public string CONOTE
		{
			get
			{
				return this._CONOTE;
			}
			set
			{
				if ((this._CONOTE != value))
				{
					this.OnCONOTEChanging(value);
					this.SendPropertyChanging();
					this._CONOTE = value;
					this.SendPropertyChanged("CONOTE");
					this.OnCONOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_CLESCOMPTE", DbType="Float NOT NULL")]
		public double CLIENT_CLESCOMPTE
		{
			get
			{
				return this._CLIENT_CLESCOMPTE;
			}
			set
			{
				if ((this._CLIENT_CLESCOMPTE != value))
				{
					this.OnCLIENT_CLESCOMPTEChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_CLESCOMPTE = value;
					this.SendPropertyChanged("CLIENT_CLESCOMPTE");
					this.OnCLIENT_CLESCOMPTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_CLALCSEQ", DbType="Int")]
		public System.Nullable<int> CLIENT_CLALCSEQ
		{
			get
			{
				return this._CLIENT_CLALCSEQ;
			}
			set
			{
				if ((this._CLIENT_CLALCSEQ != value))
				{
					this.OnCLIENT_CLALCSEQChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_CLALCSEQ = value;
					this.SendPropertyChanged("CLIENT_CLALCSEQ");
					this.OnCLIENT_CLALCSEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOTE_EXP", DbType="VarChar(7500)")]
		public string CONOTE_EXP
		{
			get
			{
				return this._CONOTE_EXP;
			}
			set
			{
				if ((this._CONOTE_EXP != value))
				{
					this.OnCONOTE_EXPChanging(value);
					this.SendPropertyChanging();
					this._CONOTE_EXP = value;
					this.SendPropertyChanged("CONOTE_EXP");
					this.OnCONOTE_EXPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALCOMPTETRANS", DbType="VarChar(20)")]
		public string ADRLIV_ALCOMPTETRANS
		{
			get
			{
				return this._ADRLIV_ALCOMPTETRANS;
			}
			set
			{
				if ((this._ADRLIV_ALCOMPTETRANS != value))
				{
					this.OnADRLIV_ALCOMPTETRANSChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALCOMPTETRANS = value;
					this.SendPropertyChanged("ADRLIV_ALCOMPTETRANS");
					this.OnADRLIV_ALCOMPTETRANSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVISES", DbType="Int")]
		public System.Nullable<int> DEVISES
		{
			get
			{
				return this._DEVISES;
			}
			set
			{
				if ((this._DEVISES != value))
				{
					this.OnDEVISESChanging(value);
					this.SendPropertyChanging();
					this._DEVISES = value;
					this.SendPropertyChanged("DEVISES");
					this.OnDEVISESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVISES_DEVCODE", DbType="Char(3)")]
		public string DEVISES_DEVCODE
		{
			get
			{
				return this._DEVISES_DEVCODE;
			}
			set
			{
				if ((this._DEVISES_DEVCODE != value))
				{
					this.OnDEVISES_DEVCODEChanging(value);
					this.SendPropertyChanging();
					this._DEVISES_DEVCODE = value;
					this.SendPropertyChanged("DEVISES_DEVCODE");
					this.OnDEVISES_DEVCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVISES_DEVDESC_P", DbType="VarChar(50)")]
		public string DEVISES_DEVDESC_P
		{
			get
			{
				return this._DEVISES_DEVDESC_P;
			}
			set
			{
				if ((this._DEVISES_DEVDESC_P != value))
				{
					this.OnDEVISES_DEVDESC_PChanging(value);
					this.SendPropertyChanging();
					this._DEVISES_DEVDESC_P = value;
					this.SendPropertyChanged("DEVISES_DEVDESC_P");
					this.OnDEVISES_DEVDESC_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVISES_DEVDESC_S", DbType="VarChar(50)")]
		public string DEVISES_DEVDESC_S
		{
			get
			{
				return this._DEVISES_DEVDESC_S;
			}
			set
			{
				if ((this._DEVISES_DEVDESC_S != value))
				{
					this.OnDEVISES_DEVDESC_SChanging(value);
					this.SendPropertyChanging();
					this._DEVISES_DEVDESC_S = value;
					this.SendPropertyChanged("DEVISES_DEVDESC_S");
					this.OnDEVISES_DEVDESC_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALTRANSTAXAB", DbType="Bit NOT NULL")]
		public bool ADRLIV_ALTRANSTAXAB
		{
			get
			{
				return this._ADRLIV_ALTRANSTAXAB;
			}
			set
			{
				if ((this._ADRLIV_ALTRANSTAXAB != value))
				{
					this.OnADRLIV_ALTRANSTAXABChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALTRANSTAXAB = value;
					this.SendPropertyChanged("ADRLIV_ALTRANSTAXAB");
					this.OnADRLIV_ALTRANSTAXABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVISES_DEVTAUX", DbType="Float NOT NULL")]
		public double DEVISES_DEVTAUX
		{
			get
			{
				return this._DEVISES_DEVTAUX;
			}
			set
			{
				if ((this._DEVISES_DEVTAUX != value))
				{
					this.OnDEVISES_DEVTAUXChanging(value);
					this.SendPropertyChanging();
					this._DEVISES_DEVTAUX = value;
					this.SendPropertyChanged("DEVISES_DEVTAUX");
					this.OnDEVISES_DEVTAUXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTNTAXE1", DbType="Float NOT NULL")]
		public double CODETAXE_CTNTAXE1
		{
			get
			{
				return this._CODETAXE_CTNTAXE1;
			}
			set
			{
				if ((this._CODETAXE_CTNTAXE1 != value))
				{
					this.OnCODETAXE_CTNTAXE1Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTNTAXE1 = value;
					this.SendPropertyChanged("CODETAXE_CTNTAXE1");
					this.OnCODETAXE_CTNTAXE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTNTAXE2", DbType="Float NOT NULL")]
		public double CODETAXE_CTNTAXE2
		{
			get
			{
				return this._CODETAXE_CTNTAXE2;
			}
			set
			{
				if ((this._CODETAXE_CTNTAXE2 != value))
				{
					this.OnCODETAXE_CTNTAXE2Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTNTAXE2 = value;
					this.SendPropertyChanged("CODETAXE_CTNTAXE2");
					this.OnCODETAXE_CTNTAXE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTNTAXE3", DbType="Float NOT NULL")]
		public double CODETAXE_CTNTAXE3
		{
			get
			{
				return this._CODETAXE_CTNTAXE3;
			}
			set
			{
				if ((this._CODETAXE_CTNTAXE3 != value))
				{
					this.OnCODETAXE_CTNTAXE3Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTNTAXE3 = value;
					this.SendPropertyChanged("CODETAXE_CTNTAXE3");
					this.OnCODETAXE_CTNTAXE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTAXE1", DbType="VarChar(20)")]
		public string CODETAXE_CTAXE1
		{
			get
			{
				return this._CODETAXE_CTAXE1;
			}
			set
			{
				if ((this._CODETAXE_CTAXE1 != value))
				{
					this.OnCODETAXE_CTAXE1Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTAXE1 = value;
					this.SendPropertyChanged("CODETAXE_CTAXE1");
					this.OnCODETAXE_CTAXE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTAXE2", DbType="VarChar(20)")]
		public string CODETAXE_CTAXE2
		{
			get
			{
				return this._CODETAXE_CTAXE2;
			}
			set
			{
				if ((this._CODETAXE_CTAXE2 != value))
				{
					this.OnCODETAXE_CTAXE2Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTAXE2 = value;
					this.SendPropertyChanged("CODETAXE_CTAXE2");
					this.OnCODETAXE_CTAXE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTAXE3", DbType="VarChar(20)")]
		public string CODETAXE_CTAXE3
		{
			get
			{
				return this._CODETAXE_CTAXE3;
			}
			set
			{
				if ((this._CODETAXE_CTAXE3 != value))
				{
					this.OnCODETAXE_CTAXE3Changing(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTAXE3 = value;
					this.SendPropertyChanged("CODETAXE_CTAXE3");
					this.OnCODETAXE_CTAXE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTAXECUMUL", DbType="Bit NOT NULL")]
		public bool CODETAXE_CTAXECUMUL
		{
			get
			{
				return this._CODETAXE_CTAXECUMUL;
			}
			set
			{
				if ((this._CODETAXE_CTAXECUMUL != value))
				{
					this.OnCODETAXE_CTAXECUMULChanging(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTAXECUMUL = value;
					this.SendPropertyChanged("CODETAXE_CTAXECUMUL");
					this.OnCODETAXE_CTAXECUMULChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODETAXE_CTCODE", DbType="VarChar(5)")]
		public string CODETAXE_CTCODE
		{
			get
			{
				return this._CODETAXE_CTCODE;
			}
			set
			{
				if ((this._CODETAXE_CTCODE != value))
				{
					this.OnCODETAXE_CTCODEChanging(value);
					this.SendPropertyChanging();
					this._CODETAXE_CTCODE = value;
					this.SendPropertyChanged("CODETAXE_CTCODE");
					this.OnCODETAXE_CTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COPROJET", DbType="VarChar(50)")]
		public string COPROJET
		{
			get
			{
				return this._COPROJET;
			}
			set
			{
				if ((this._COPROJET != value))
				{
					this.OnCOPROJETChanging(value);
					this.SendPropertyChanging();
					this._COPROJET = value;
					this.SendPropertyChanged("COPROJET");
					this.OnCOPROJETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COEXPORTE", DbType="Bit")]
		public System.Nullable<bool> COEXPORTE
		{
			get
			{
				return this._COEXPORTE;
			}
			set
			{
				if ((this._COEXPORTE != value))
				{
					this.OnCOEXPORTEChanging(value);
					this.SendPropertyChanging();
					this._COEXPORTE = value;
					this.SendPropertyChanged("COEXPORTE");
					this.OnCOEXPORTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COACHETEUR", DbType="VarChar(50)")]
		public string COACHETEUR
		{
			get
			{
				return this._COACHETEUR;
			}
			set
			{
				if ((this._COACHETEUR != value))
				{
					this.OnCOACHETEURChanging(value);
					this.SendPropertyChanging();
					this._COACHETEUR = value;
					this.SendPropertyChanged("COACHETEUR");
					this.OnCOACHETEURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUSAGER", DbType="VarChar(50)")]
		public string COUSAGER
		{
			get
			{
				return this._COUSAGER;
			}
			set
			{
				if ((this._COUSAGER != value))
				{
					this.OnCOUSAGERChanging(value);
					this.SendPropertyChanging();
					this._COUSAGER = value;
					this.SendPropertyChanged("COUSAGER");
					this.OnCOUSAGERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COAUSOIN_DE", DbType="VarChar(60)")]
		public string COAUSOIN_DE
		{
			get
			{
				return this._COAUSOIN_DE;
			}
			set
			{
				if ((this._COAUSOIN_DE != value))
				{
					this.OnCOAUSOIN_DEChanging(value);
					this.SendPropertyChanging();
					this._COAUSOIN_DE = value;
					this.SendPropertyChanged("COAUSOIN_DE");
					this.OnCOAUSOIN_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTAXE1", DbType="Float NOT NULL")]
		public double COTAXE1
		{
			get
			{
				return this._COTAXE1;
			}
			set
			{
				if ((this._COTAXE1 != value))
				{
					this.OnCOTAXE1Changing(value);
					this.SendPropertyChanging();
					this._COTAXE1 = value;
					this.SendPropertyChanged("COTAXE1");
					this.OnCOTAXE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTAXE2", DbType="Float NOT NULL")]
		public double COTAXE2
		{
			get
			{
				return this._COTAXE2;
			}
			set
			{
				if ((this._COTAXE2 != value))
				{
					this.OnCOTAXE2Changing(value);
					this.SendPropertyChanging();
					this._COTAXE2 = value;
					this.SendPropertyChanged("COTAXE2");
					this.OnCOTAXE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTAXE3", DbType="Float NOT NULL")]
		public double COTAXE3
		{
			get
			{
				return this._COTAXE3;
			}
			set
			{
				if ((this._COTAXE3 != value))
				{
					this.OnCOTAXE3Changing(value);
					this.SendPropertyChanging();
					this._COTAXE3 = value;
					this.SendPropertyChanged("COTAXE3");
					this.OnCOTAXE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMONTANTTAXABLE", DbType="Float NOT NULL")]
		public double COMONTANTTAXABLE
		{
			get
			{
				return this._COMONTANTTAXABLE;
			}
			set
			{
				if ((this._COMONTANTTAXABLE != value))
				{
					this.OnCOMONTANTTAXABLEChanging(value);
					this.SendPropertyChanging();
					this._COMONTANTTAXABLE = value;
					this.SendPropertyChanged("COMONTANTTAXABLE");
					this.OnCOMONTANTTAXABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSOUSTOTAL", DbType="Float NOT NULL")]
		public double COSOUSTOTAL
		{
			get
			{
				return this._COSOUSTOTAL;
			}
			set
			{
				if ((this._COSOUSTOTAL != value))
				{
					this.OnCOSOUSTOTALChanging(value);
					this.SendPropertyChanging();
					this._COSOUSTOTAL = value;
					this.SendPropertyChanged("COSOUSTOTAL");
					this.OnCOSOUSTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_CLINDEFINI", DbType="Bit NOT NULL")]
		public bool CLIENT_CLINDEFINI
		{
			get
			{
				return this._CLIENT_CLINDEFINI;
			}
			set
			{
				if ((this._CLIENT_CLINDEFINI != value))
				{
					this.OnCLIENT_CLINDEFINIChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_CLINDEFINI = value;
					this.SendPropertyChanged("CLIENT_CLINDEFINI");
					this.OnCLIENT_CLINDEFINIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC", DbType="Int")]
		public System.Nullable<int> ADRFAC
		{
			get
			{
				return this._ADRFAC;
			}
			set
			{
				if ((this._ADRFAC != value))
				{
					this.OnADRFACChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC = value;
					this.SendPropertyChanged("ADRFAC");
					this.OnADRFACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALSOINDE", DbType="VarChar(60)")]
		public string ADRFAC_ALSOINDE
		{
			get
			{
				return this._ADRFAC_ALSOINDE;
			}
			set
			{
				if ((this._ADRFAC_ALSOINDE != value))
				{
					this.OnADRFAC_ALSOINDEChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALSOINDE = value;
					this.SendPropertyChanged("ADRFAC_ALSOINDE");
					this.OnADRFAC_ALSOINDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALNOM", DbType="VarChar(50)")]
		public string ADRFAC_ALNOM
		{
			get
			{
				return this._ADRFAC_ALNOM;
			}
			set
			{
				if ((this._ADRFAC_ALNOM != value))
				{
					this.OnADRFAC_ALNOMChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALNOM = value;
					this.SendPropertyChanged("ADRFAC_ALNOM");
					this.OnADRFAC_ALNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALADR1", DbType="VarChar(50)")]
		public string ADRFAC_ALADR1
		{
			get
			{
				return this._ADRFAC_ALADR1;
			}
			set
			{
				if ((this._ADRFAC_ALADR1 != value))
				{
					this.OnADRFAC_ALADR1Changing(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALADR1 = value;
					this.SendPropertyChanged("ADRFAC_ALADR1");
					this.OnADRFAC_ALADR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALADR2", DbType="VarChar(50)")]
		public string ADRFAC_ALADR2
		{
			get
			{
				return this._ADRFAC_ALADR2;
			}
			set
			{
				if ((this._ADRFAC_ALADR2 != value))
				{
					this.OnADRFAC_ALADR2Changing(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALADR2 = value;
					this.SendPropertyChanged("ADRFAC_ALADR2");
					this.OnADRFAC_ALADR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALADR3", DbType="VarChar(50)")]
		public string ADRFAC_ALADR3
		{
			get
			{
				return this._ADRFAC_ALADR3;
			}
			set
			{
				if ((this._ADRFAC_ALADR3 != value))
				{
					this.OnADRFAC_ALADR3Changing(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALADR3 = value;
					this.SendPropertyChanged("ADRFAC_ALADR3");
					this.OnADRFAC_ALADR3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALADR4", DbType="VarChar(50)")]
		public string ADRFAC_ALADR4
		{
			get
			{
				return this._ADRFAC_ALADR4;
			}
			set
			{
				if ((this._ADRFAC_ALADR4 != value))
				{
					this.OnADRFAC_ALADR4Changing(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALADR4 = value;
					this.SendPropertyChanged("ADRFAC_ALADR4");
					this.OnADRFAC_ALADR4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALADR5", DbType="VarChar(50)")]
		public string ADRFAC_ALADR5
		{
			get
			{
				return this._ADRFAC_ALADR5;
			}
			set
			{
				if ((this._ADRFAC_ALADR5 != value))
				{
					this.OnADRFAC_ALADR5Changing(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALADR5 = value;
					this.SendPropertyChanged("ADRFAC_ALADR5");
					this.OnADRFAC_ALADR5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_FM_LANGUE", DbType="Int")]
		public System.Nullable<int> ADRFAC_FM_LANGUE
		{
			get
			{
				return this._ADRFAC_FM_LANGUE;
			}
			set
			{
				if ((this._ADRFAC_FM_LANGUE != value))
				{
					this.OnADRFAC_FM_LANGUEChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_FM_LANGUE = value;
					this.SendPropertyChanged("ADRFAC_FM_LANGUE");
					this.OnADRFAC_FM_LANGUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRITOIRE_TTCODE", DbType="VarChar(3)")]
		public string TERRITOIRE_TTCODE
		{
			get
			{
				return this._TERRITOIRE_TTCODE;
			}
			set
			{
				if ((this._TERRITOIRE_TTCODE != value))
				{
					this.OnTERRITOIRE_TTCODEChanging(value);
					this.SendPropertyChanging();
					this._TERRITOIRE_TTCODE = value;
					this.SendPropertyChanged("TERRITOIRE_TTCODE");
					this.OnTERRITOIRE_TTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRLIV_ALEXTENSION", DbType="VarChar(50)")]
		public string ADRLIV_ALEXTENSION
		{
			get
			{
				return this._ADRLIV_ALEXTENSION;
			}
			set
			{
				if ((this._ADRLIV_ALEXTENSION != value))
				{
					this.OnADRLIV_ALEXTENSIONChanging(value);
					this.SendPropertyChanging();
					this._ADRLIV_ALEXTENSION = value;
					this.SendPropertyChanged("ADRLIV_ALEXTENSION");
					this.OnADRLIV_ALEXTENSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOURNISSEUR_ADRLIV", DbType="Int")]
		public System.Nullable<int> FOURNISSEUR_ADRLIV
		{
			get
			{
				return this._FOURNISSEUR_ADRLIV;
			}
			set
			{
				if ((this._FOURNISSEUR_ADRLIV != value))
				{
					this.OnFOURNISSEUR_ADRLIVChanging(value);
					this.SendPropertyChanging();
					this._FOURNISSEUR_ADRLIV = value;
					this.SendPropertyChanged("FOURNISSEUR_ADRLIV");
					this.OnFOURNISSEUR_ADRLIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTOTALITEM", DbType="Float NOT NULL")]
		public double COTOTALITEM
		{
			get
			{
				return this._COTOTALITEM;
			}
			set
			{
				if ((this._COTOTALITEM != value))
				{
					this.OnCOTOTALITEMChanging(value);
					this.SendPropertyChanging();
					this._COTOTALITEM = value;
					this.SendPropertyChanged("COTOTALITEM");
					this.OnCOTOTALITEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOTE_TRANSPORT", DbType="VarChar(7500)")]
		public string CONOTE_TRANSPORT
		{
			get
			{
				return this._CONOTE_TRANSPORT;
			}
			set
			{
				if ((this._CONOTE_TRANSPORT != value))
				{
					this.OnCONOTE_TRANSPORTChanging(value);
					this.SendPropertyChanging();
					this._CONOTE_TRANSPORT = value;
					this.SendPropertyChanged("CONOTE_TRANSPORT");
					this.OnCONOTE_TRANSPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="Int")]
		public System.Nullable<int> CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this.OnCONTACTChanging(value);
					this.SendPropertyChanging();
					this._CONTACT = value;
					this.SendPropertyChanged("CONTACT");
					this.OnCONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_FAC", DbType="Int")]
		public System.Nullable<int> CLIENT_FAC
		{
			get
			{
				return this._CLIENT_FAC;
			}
			set
			{
				if ((this._CLIENT_FAC != value))
				{
					this.OnCLIENT_FACChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_FAC = value;
					this.SendPropertyChanged("CLIENT_FAC");
					this.OnCLIENT_FACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_FAC_CLCODE", DbType="VarChar(20)")]
		public string CLIENT_FAC_CLCODE
		{
			get
			{
				return this._CLIENT_FAC_CLCODE;
			}
			set
			{
				if ((this._CLIENT_FAC_CLCODE != value))
				{
					this.OnCLIENT_FAC_CLCODEChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_FAC_CLCODE = value;
					this.SendPropertyChanged("CLIENT_FAC_CLCODE");
					this.OnCLIENT_FAC_CLCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_FAC_CLNOM", DbType="VarChar(50)")]
		public string CLIENT_FAC_CLNOM
		{
			get
			{
				return this._CLIENT_FAC_CLNOM;
			}
			set
			{
				if ((this._CLIENT_FAC_CLNOM != value))
				{
					this.OnCLIENT_FAC_CLNOMChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_FAC_CLNOM = value;
					this.SendPropertyChanged("CLIENT_FAC_CLNOM");
					this.OnCLIENT_FAC_CLNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COCHEMCOPIEDESS_SE", DbType="VarChar(255)")]
		public string COCHEMCOPIEDESS_SE
		{
			get
			{
				return this._COCHEMCOPIEDESS_SE;
			}
			set
			{
				if ((this._COCHEMCOPIEDESS_SE != value))
				{
					this.OnCOCHEMCOPIEDESS_SEChanging(value);
					this.SendPropertyChanging();
					this._COCHEMCOPIEDESS_SE = value;
					this.SendPropertyChanged("COCHEMCOPIEDESS_SE");
					this.OnCOCHEMCOPIEDESS_SEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COPRIX_FIXE", DbType="Bit NOT NULL")]
		public bool COPRIX_FIXE
		{
			get
			{
				return this._COPRIX_FIXE;
			}
			set
			{
				if ((this._COPRIX_FIXE != value))
				{
					this.OnCOPRIX_FIXEChanging(value);
					this.SendPropertyChanging();
					this._COPRIX_FIXE = value;
					this.SendPropertyChanged("COPRIX_FIXE");
					this.OnCOPRIX_FIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAISON", DbType="Int")]
		public System.Nullable<int> RAISON
		{
			get
			{
				return this._RAISON;
			}
			set
			{
				if ((this._RAISON != value))
				{
					this.OnRAISONChanging(value);
					this.SendPropertyChanging();
					this._RAISON = value;
					this.SendPropertyChanged("RAISON");
					this.OnRAISONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAISON_RRCODE", DbType="VarChar(20)")]
		public string RAISON_RRCODE
		{
			get
			{
				return this._RAISON_RRCODE;
			}
			set
			{
				if ((this._RAISON_RRCODE != value))
				{
					this.OnRAISON_RRCODEChanging(value);
					this.SendPropertyChanging();
					this._RAISON_RRCODE = value;
					this.SendPropertyChanged("RAISON_RRCODE");
					this.OnRAISON_RRCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAISON_RRDESC_P", DbType="VarChar(50)")]
		public string RAISON_RRDESC_P
		{
			get
			{
				return this._RAISON_RRDESC_P;
			}
			set
			{
				if ((this._RAISON_RRDESC_P != value))
				{
					this.OnRAISON_RRDESC_PChanging(value);
					this.SendPropertyChanging();
					this._RAISON_RRDESC_P = value;
					this.SendPropertyChanged("RAISON_RRDESC_P");
					this.OnRAISON_RRDESC_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAISON_RRDESC_S", DbType="VarChar(50)")]
		public string RAISON_RRDESC_S
		{
			get
			{
				return this._RAISON_RRDESC_S;
			}
			set
			{
				if ((this._RAISON_RRDESC_S != value))
				{
					this.OnRAISON_RRDESC_SChanging(value);
					this.SendPropertyChanging();
					this._RAISON_RRDESC_S = value;
					this.SendPropertyChanged("RAISON_RRDESC_S");
					this.OnRAISON_RRDESC_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONOCONTRAT", DbType="VarChar(15)")]
		public string CONOCONTRAT
		{
			get
			{
				return this._CONOCONTRAT;
			}
			set
			{
				if ((this._CONOCONTRAT != value))
				{
					this.OnCONOCONTRATChanging(value);
					this.SendPropertyChanging();
					this._CONOCONTRAT = value;
					this.SendPropertyChanged("CONOCONTRAT");
					this.OnCONOCONTRATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COCLOSEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> COCLOSEDATE
		{
			get
			{
				return this._COCLOSEDATE;
			}
			set
			{
				if ((this._COCLOSEDATE != value))
				{
					this.OnCOCLOSEDATEChanging(value);
					this.SendPropertyChanging();
					this._COCLOSEDATE = value;
					this.SendPropertyChanged("COCLOSEDATE");
					this.OnCOCLOSEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALFAX", DbType="VarChar(20)")]
		public string ADRFAC_ALFAX
		{
			get
			{
				return this._ADRFAC_ALFAX;
			}
			set
			{
				if ((this._ADRFAC_ALFAX != value))
				{
					this.OnADRFAC_ALFAXChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALFAX = value;
					this.SendPropertyChanged("ADRFAC_ALFAX");
					this.OnADRFAC_ALFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALTEL", DbType="VarChar(20)")]
		public string ADRFAC_ALTEL
		{
			get
			{
				return this._ADRFAC_ALTEL;
			}
			set
			{
				if ((this._ADRFAC_ALTEL != value))
				{
					this.OnADRFAC_ALTELChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALTEL = value;
					this.SendPropertyChanged("ADRFAC_ALTEL");
					this.OnADRFAC_ALTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALEMAIL", DbType="VarChar(100)")]
		public string ADRFAC_ALEMAIL
		{
			get
			{
				return this._ADRFAC_ALEMAIL;
			}
			set
			{
				if ((this._ADRFAC_ALEMAIL != value))
				{
					this.OnADRFAC_ALEMAILChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALEMAIL = value;
					this.SendPropertyChanged("ADRFAC_ALEMAIL");
					this.OnADRFAC_ALEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALCONTACT", DbType="VarChar(50)")]
		public string ADRFAC_ALCONTACT
		{
			get
			{
				return this._ADRFAC_ALCONTACT;
			}
			set
			{
				if ((this._ADRFAC_ALCONTACT != value))
				{
					this.OnADRFAC_ALCONTACTChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALCONTACT = value;
					this.SendPropertyChanged("ADRFAC_ALCONTACT");
					this.OnADRFAC_ALCONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALCELLULAIRE", DbType="VarChar(20)")]
		public string ADRFAC_ALCELLULAIRE
		{
			get
			{
				return this._ADRFAC_ALCELLULAIRE;
			}
			set
			{
				if ((this._ADRFAC_ALCELLULAIRE != value))
				{
					this.OnADRFAC_ALCELLULAIREChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALCELLULAIRE = value;
					this.SendPropertyChanged("ADRFAC_ALCELLULAIRE");
					this.OnADRFAC_ALCELLULAIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRFAC_ALTELAUTRE", DbType="VarChar(50)")]
		public string ADRFAC_ALTELAUTRE
		{
			get
			{
				return this._ADRFAC_ALTELAUTRE;
			}
			set
			{
				if ((this._ADRFAC_ALTELAUTRE != value))
				{
					this.OnADRFAC_ALTELAUTREChanging(value);
					this.SendPropertyChanging();
					this._ADRFAC_ALTELAUTRE = value;
					this.SendPropertyChanged("ADRFAC_ALTELAUTRE");
					this.OnADRFAC_ALTELAUTREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSEQ_PERE", DbType="Int")]
		public System.Nullable<int> COSEQ_PERE
		{
			get
			{
				return this._COSEQ_PERE;
			}
			set
			{
				if ((this._COSEQ_PERE != value))
				{
					this.OnCOSEQ_PEREChanging(value);
					this.SendPropertyChanging();
					this._COSEQ_PERE = value;
					this.SendPropertyChanged("COSEQ_PERE");
					this.OnCOSEQ_PEREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COCOMPTEUR_REVISION", DbType="Int NOT NULL")]
		public int COCOMPTEUR_REVISION
		{
			get
			{
				return this._COCOMPTEUR_REVISION;
			}
			set
			{
				if ((this._COCOMPTEUR_REVISION != value))
				{
					this.OnCOCOMPTEUR_REVISIONChanging(value);
					this.SendPropertyChanging();
					this._COCOMPTEUR_REVISION = value;
					this.SendPropertyChanged("COCOMPTEUR_REVISION");
					this.OnCOCOMPTEUR_REVISIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COREVNOTRANS", DbType="Char(10)")]
		public string COREVNOTRANS
		{
			get
			{
				return this._COREVNOTRANS;
			}
			set
			{
				if ((this._COREVNOTRANS != value))
				{
					this.OnCOREVNOTRANSChanging(value);
					this.SendPropertyChanging();
					this._COREVNOTRANS = value;
					this.SendPropertyChanged("COREVNOTRANS");
					this.OnCOREVNOTRANSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COINFOSUP", DbType="VarChar(50)")]
		public string COINFOSUP
		{
			get
			{
				return this._COINFOSUP;
			}
			set
			{
				if ((this._COINFOSUP != value))
				{
					this.OnCOINFOSUPChanging(value);
					this.SendPropertyChanging();
					this._COINFOSUP = value;
					this.SendPropertyChanged("COINFOSUP");
					this.OnCOINFOSUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCUMENT")]
	public partial class DOCUMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DOSEQ;
		
		private string _DONOM_TABLE;
		
		private int _DOSEQ_REFERENCE;
		
		private byte _DOTYPE_IMPRESSION;
		
		private int _DOORDRE;
		
		private string _DODESC_P;
		
		private string _DODESC_S;
		
		private string _DOFICHIER;
		
		private string _DONOTE;
		
		private System.DateTime _DODATE;
		
		private string _DOUSAGER;
		
		private string _DOVERSION_NEWS;
		
		private System.Data.Linq.Binary _DOBLOB;
		
		private string _DOIMP_PROC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOSEQChanging(int value);
    partial void OnDOSEQChanged();
    partial void OnDONOM_TABLEChanging(string value);
    partial void OnDONOM_TABLEChanged();
    partial void OnDOSEQ_REFERENCEChanging(int value);
    partial void OnDOSEQ_REFERENCEChanged();
    partial void OnDOTYPE_IMPRESSIONChanging(byte value);
    partial void OnDOTYPE_IMPRESSIONChanged();
    partial void OnDOORDREChanging(int value);
    partial void OnDOORDREChanged();
    partial void OnDODESC_PChanging(string value);
    partial void OnDODESC_PChanged();
    partial void OnDODESC_SChanging(string value);
    partial void OnDODESC_SChanged();
    partial void OnDOFICHIERChanging(string value);
    partial void OnDOFICHIERChanged();
    partial void OnDONOTEChanging(string value);
    partial void OnDONOTEChanged();
    partial void OnDODATEChanging(System.DateTime value);
    partial void OnDODATEChanged();
    partial void OnDOUSAGERChanging(string value);
    partial void OnDOUSAGERChanged();
    partial void OnDOVERSION_NEWSChanging(string value);
    partial void OnDOVERSION_NEWSChanged();
    partial void OnDOBLOBChanging(System.Data.Linq.Binary value);
    partial void OnDOBLOBChanged();
    partial void OnDOIMP_PROCChanging(string value);
    partial void OnDOIMP_PROCChanged();
    #endregion
		
		public DOCUMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSEQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DOSEQ
		{
			get
			{
				return this._DOSEQ;
			}
			set
			{
				if ((this._DOSEQ != value))
				{
					this.OnDOSEQChanging(value);
					this.SendPropertyChanging();
					this._DOSEQ = value;
					this.SendPropertyChanged("DOSEQ");
					this.OnDOSEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONOM_TABLE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DONOM_TABLE
		{
			get
			{
				return this._DONOM_TABLE;
			}
			set
			{
				if ((this._DONOM_TABLE != value))
				{
					this.OnDONOM_TABLEChanging(value);
					this.SendPropertyChanging();
					this._DONOM_TABLE = value;
					this.SendPropertyChanged("DONOM_TABLE");
					this.OnDONOM_TABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSEQ_REFERENCE", DbType="Int NOT NULL")]
		public int DOSEQ_REFERENCE
		{
			get
			{
				return this._DOSEQ_REFERENCE;
			}
			set
			{
				if ((this._DOSEQ_REFERENCE != value))
				{
					this.OnDOSEQ_REFERENCEChanging(value);
					this.SendPropertyChanging();
					this._DOSEQ_REFERENCE = value;
					this.SendPropertyChanged("DOSEQ_REFERENCE");
					this.OnDOSEQ_REFERENCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOTYPE_IMPRESSION", DbType="TinyInt NOT NULL")]
		public byte DOTYPE_IMPRESSION
		{
			get
			{
				return this._DOTYPE_IMPRESSION;
			}
			set
			{
				if ((this._DOTYPE_IMPRESSION != value))
				{
					this.OnDOTYPE_IMPRESSIONChanging(value);
					this.SendPropertyChanging();
					this._DOTYPE_IMPRESSION = value;
					this.SendPropertyChanged("DOTYPE_IMPRESSION");
					this.OnDOTYPE_IMPRESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOORDRE", DbType="Int NOT NULL")]
		public int DOORDRE
		{
			get
			{
				return this._DOORDRE;
			}
			set
			{
				if ((this._DOORDRE != value))
				{
					this.OnDOORDREChanging(value);
					this.SendPropertyChanging();
					this._DOORDRE = value;
					this.SendPropertyChanged("DOORDRE");
					this.OnDOORDREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DODESC_P", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DODESC_P
		{
			get
			{
				return this._DODESC_P;
			}
			set
			{
				if ((this._DODESC_P != value))
				{
					this.OnDODESC_PChanging(value);
					this.SendPropertyChanging();
					this._DODESC_P = value;
					this.SendPropertyChanged("DODESC_P");
					this.OnDODESC_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DODESC_S", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DODESC_S
		{
			get
			{
				return this._DODESC_S;
			}
			set
			{
				if ((this._DODESC_S != value))
				{
					this.OnDODESC_SChanging(value);
					this.SendPropertyChanging();
					this._DODESC_S = value;
					this.SendPropertyChanged("DODESC_S");
					this.OnDODESC_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOFICHIER", DbType="VarChar(256)")]
		public string DOFICHIER
		{
			get
			{
				return this._DOFICHIER;
			}
			set
			{
				if ((this._DOFICHIER != value))
				{
					this.OnDOFICHIERChanging(value);
					this.SendPropertyChanging();
					this._DOFICHIER = value;
					this.SendPropertyChanged("DOFICHIER");
					this.OnDOFICHIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONOTE", DbType="VarChar(7500)")]
		public string DONOTE
		{
			get
			{
				return this._DONOTE;
			}
			set
			{
				if ((this._DONOTE != value))
				{
					this.OnDONOTEChanging(value);
					this.SendPropertyChanging();
					this._DONOTE = value;
					this.SendPropertyChanged("DONOTE");
					this.OnDONOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DODATE", DbType="DateTime NOT NULL")]
		public System.DateTime DODATE
		{
			get
			{
				return this._DODATE;
			}
			set
			{
				if ((this._DODATE != value))
				{
					this.OnDODATEChanging(value);
					this.SendPropertyChanging();
					this._DODATE = value;
					this.SendPropertyChanged("DODATE");
					this.OnDODATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOUSAGER", DbType="VarChar(50)")]
		public string DOUSAGER
		{
			get
			{
				return this._DOUSAGER;
			}
			set
			{
				if ((this._DOUSAGER != value))
				{
					this.OnDOUSAGERChanging(value);
					this.SendPropertyChanging();
					this._DOUSAGER = value;
					this.SendPropertyChanged("DOUSAGER");
					this.OnDOUSAGERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOVERSION_NEWS", DbType="VarChar(10)")]
		public string DOVERSION_NEWS
		{
			get
			{
				return this._DOVERSION_NEWS;
			}
			set
			{
				if ((this._DOVERSION_NEWS != value))
				{
					this.OnDOVERSION_NEWSChanging(value);
					this.SendPropertyChanging();
					this._DOVERSION_NEWS = value;
					this.SendPropertyChanged("DOVERSION_NEWS");
					this.OnDOVERSION_NEWSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOBLOB", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DOBLOB
		{
			get
			{
				return this._DOBLOB;
			}
			set
			{
				if ((this._DOBLOB != value))
				{
					this.OnDOBLOBChanging(value);
					this.SendPropertyChanging();
					this._DOBLOB = value;
					this.SendPropertyChanged("DOBLOB");
					this.OnDOBLOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOIMP_PROC", DbType="VarChar(500)")]
		public string DOIMP_PROC
		{
			get
			{
				return this._DOIMP_PROC;
			}
			set
			{
				if ((this._DOIMP_PROC != value))
				{
					this.OnDOIMP_PROCChanging(value);
					this.SendPropertyChanging();
					this._DOIMP_PROC = value;
					this.SendPropertyChanged("DOIMP_PROC");
					this.OnDOIMP_PROCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
